name: Deploy Chinese Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        DEFAULT_LOCALE: zh
    
    - name: Deploy to Railway (Chinese)
      uses: railway-app/railway@v1
      with:
        service: telehealth-chinese
        token: ${{ secrets.RAILWAY_TOKEN }}
        config: railway-chinese.toml